set -g prefix C-x
unbind C-b
bind C-x send-prefix
bind e split-window -h
bind o split-window -v
unbind '"'
unbind %
set -g window-status-style bg=yellow
set -g window-status-current-style bg=red,fg=white
bind w kill-pane
bind q kill-window
unbind &
setw -g mode-keys vi
bind l select-pane -D
bind k select-pane -U
bind j select-pane -R 
bind ";" select-pane -L  
